#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <socapp_icons.h>

int32_t socapp_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm socapp!");

    return 0;
}
